version: "3.8"

services:
  cassandra:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab-3-cassandra-1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
    volumes:
      - ./resources:/resources
